import { expect, test } from "@playwright/test";

const installProviderMocks = async (page: Parameters<typeof test>[0] extends never ? never : any) => { await page.route("https://api.openai.com/v1/models", async (route: any) => route.fulfill({ contentType: "application/json", body: JSON.stringify({ data: [{ id: "test-model", owned_by: "test" }] }) })); };
async function addProvider(page: any) { await page.getByRole("button", { name: /Add provider/i }).first().click(); await page.getByRole("textbox", { name: "API key" }).fill("YOUR_API_KEY"); await page.getByRole("button", { name: "Test connection" }).click(); await expect(page.getByText(/Connection successful/)).toBeVisible(); await page.getByRole("button", { name: "Save local provider" }).click(); }
const sendFromComposer = (page: any) => page.locator(".prompt-editor").getByRole("button", { name: "Send", exact: true }).click();

test("configures a local provider, streams a response, and saves a local audit record", async ({ page }) => { await installProviderMocks(page); await page.route("https://api.openai.com/v1/chat/completions", async (route) => route.fulfill({ status: 200, contentType: "text/event-stream", body: 'data: {"choices":[{"delta":{"content":"Hello "}}]}\n\ndata: {"choices":[{"delta":{"content":"workspace"}}]}\n\ndata: [DONE]\n\n' })); await page.goto("/providers"); await addProvider(page); await page.locator(".app-sidebar").getByRole("link", { name: "Playground", exact: true }).click(); await page.getByLabel("user message").fill("Say hello"); await sendFromComposer(page); await expect(page.getByText("Hello workspace")).toBeVisible(); await expect(page.getByText("Completed").first()).toBeVisible(); await page.locator(".app-sidebar").getByRole("link", { name: "History", exact: true }).click(); await expect(page.locator(".tool-table code").filter({ hasText: "test-model" })).toBeVisible(); await expect(page.locator(".tool-table .status-indicator").filter({ hasText: "Completed" })).toBeVisible(); });
test("stops an active browser request without presenting it as a provider failure", async ({ page }) => { await installProviderMocks(page); await page.route("https://api.openai.com/v1/chat/completions", async (route) => { await new Promise((resolve) => setTimeout(resolve, 1200)); await route.fulfill({ status: 200, contentType: "text/event-stream", body: "data: [DONE]\n\n" }); }); await page.goto("/providers"); await addProvider(page); await page.locator(".app-sidebar").getByRole("link", { name: "Playground", exact: true }).click(); await page.getByLabel("user message").fill("Stop this request"); await sendFromComposer(page); await page.getByRole("button", { name: "Stop" }).first().click(); await expect(page.getByText("Aborted").first()).toBeVisible(); });
test("presents a safe authentication diagnostic without rendering the entered key", async ({ page }) => { await installProviderMocks(page); await page.route("https://api.openai.com/v1/chat/completions", async (route) => route.fulfill({ status: 401, contentType: "application/json", body: JSON.stringify({ error: { message: "Invalid key" } }) })); await page.goto("/providers"); await addProvider(page); await page.locator(".app-sidebar").getByRole("link", { name: "Playground", exact: true }).click(); await page.getByLabel("user message").fill("Fail securely"); await sendFromComposer(page); await expect(page.getByText("Invalid API Key / Authentication")).toBeVisible(); await expect(page.locator("body")).not.toContainText("YOUR_API_KEY"); });
