import { afterEach, describe, expect, it, vi } from "vitest";
import { runCompareTarget, runComparison } from "@/services/compareService";
import type { ComparePrompt, CompareTarget } from "@/domain/compare";
import type { AIResponse, ProviderConfig } from "@/domain/types";

const providerService = vi.hoisted(() => ({ sendProviderRequest: vi.fn(), streamProviderRequest: vi.fn(), normalizeProviderError: vi.fn((error: unknown) => ({ category: "unknown" as const, title: "Request failed", description: "Safe failure", message: error instanceof Error ? error.message : "Safe failure", retryable: true, causes: [], actions: ["Retry"] })) }));
vi.mock("@/services/providerService", () => providerService);
const prompt: ComparePrompt = { messages: [{ id: "system", role: "system", content: "Be precise" }, { id: "user", role: "user", content: "Compare this" }], parameters: { temperature: 0.7, maxTokens: 64, stream: false } };
const config = (id: string): ProviderConfig => ({ id, kind: "custom", name: id, baseUrl: "https://api.example.com/v1", apiKeyRef: `local:${id}`, defaultModel: "model", headers: {}, enabled: true, status: "ready", createdAt: "2026-01-01T00:00:00.000Z", updatedAt: "2026-01-01T00:00:00.000Z" });
const target = (id: string): CompareTarget => ({ id, providerId: id, providerName: id, model: `${id}-model`, displayName: id, inputPricePerMillion: 2, outputPricePerMillion: 4 });
const response = (targetId: string): AIResponse => ({ id: `response-${targetId}`, requestId: `request-${targetId}`, provider: targetId, model: `${targetId}-model`, content: `Response ${targetId}`, httpStatus: 200, headers: { "x-request-id": targetId, authorization: "never-store" }, metrics: { startedAt: "2026-01-01T00:00:00.000Z", completedAt: "2026-01-01T00:00:01.000Z", latencyMs: 100, ttftMs: 20, usage: { inputTokens: 10, outputTokens: 20, totalTokens: 30 } }, raw: {} });
afterEach(() => vi.resetAllMocks());
describe("compare execution", () => {
  it("starts up to three selected models concurrently and keeps all completed results", async () => { providerService.sendProviderRequest.mockImplementation(async (request: { providerId: string }) => response(request.providerId)); const updates: string[] = []; const targets = [target("a"), target("b"), target("c")]; const settled = await runComparison(targets, prompt, targets.map((item) => config(item.providerId)), new Map(), (result) => updates.push(`${result.targetId}:${result.status}`)); expect(settled).toHaveLength(3); expect(providerService.sendProviderRequest).toHaveBeenCalledTimes(3); expect(updates).toContain("a:completed"); expect(updates).toContain("b:completed"); expect(updates).toContain("c:completed"); });
  it("isolates a partial failure instead of failing the full comparison", async () => { providerService.sendProviderRequest.mockImplementation(async (request: { providerId: string }) => { if (request.providerId === "b") throw new Error("rate limited"); return response(request.providerId); }); const updates: Record<string, string> = {}; await runComparison([target("a"), target("b"), target("c")], prompt, [config("a"), config("b"), config("c")], new Map(), (result) => { updates[result.targetId] = result.status; }); expect(updates).toMatchObject({ a: "completed", b: "failed", c: "completed" }); });
  it("updates a streaming target incrementally and computes cost only from known prices", async () => { async function* stream() { yield { type: "stream-started" as const, at: "2026-01-01T00:00:00.000Z" }; yield { type: "delta" as const, at: "2026-01-01T00:00:00.100Z", value: "Hello " }; yield { type: "delta" as const, at: "2026-01-01T00:00:00.200Z", value: "world" }; yield { type: "completed" as const, at: "2026-01-01T00:00:01.000Z", response: response("a") }; } providerService.streamProviderRequest.mockImplementation(stream); const updates: string[] = []; const result = await runCompareTarget(target("a"), { ...prompt, parameters: { ...prompt.parameters, stream: true } }, config("a"), new AbortController().signal, (next) => updates.push(next.content)); expect(updates).toContain("Hello "); expect(result.content).toBe("Response a"); expect(result.metrics.estimatedCost).toBeCloseTo(0.0001); expect(result.headers).not.toHaveProperty("authorization"); });
  it("marks only the aborted target as aborted", async () => { providerService.sendProviderRequest.mockImplementation((_request: unknown, _config: unknown, signal: AbortSignal) => new Promise((_resolve, reject) => { signal.addEventListener("abort", () => reject(new DOMException("Aborted", "AbortError"))); })); const controller = new AbortController(); const task = runCompareTarget(target("a"), prompt, config("a"), controller.signal, () => undefined); controller.abort(); await expect(task).resolves.toMatchObject({ status: "aborted" }); });
});
