import { describe, expect, it } from "vitest";
import { diagnosticReport, safeDiagnosticHeaders } from "@/domain/diagnostics";
import { errorAnalyzer } from "@/domain/errors";

describe("Phase 6 ErrorAnalyzer", () => {
  it.each([[401, "authentication", "Invalid API Key / Authentication", false], [403, "forbidden", "Permission Denied", false], [400, "bad-request", "Invalid Request", false], [404, "not-found", "Provider Route Not Found", false], [408, "timeout", "Request Timeout", true], [413, "context-length", "Request Too Large", false], [422, "bad-request", "Invalid Request", false], [429, "rate-limit", "Rate Limit / Quota", true], [500, "server", "Internal Server Error", true], [502, "server", "Bad Gateway", true], [503, "server", "Service Unavailable", true], [504, "server", "Gateway Timeout", true]] as const)("normalizes %s as %s", (status, category, title, retryable) => { const error = errorAnalyzer.analyze({ status, message: "Provider failure" }); expect(error).toMatchObject({ status, category, title, retryable }); expect(error.causes.length).toBeGreaterThan(0); expect(error.actions.length).toBeGreaterThan(0); });
  it("distinguishes CORS, network, model, context and streaming failures", () => { expect(errorAnalyzer.analyze({ message: "CORS policy blocked this cross-origin request" }).category).toBe("cors"); expect(errorAnalyzer.analyze({ message: "DNS connection refused" }).category).toBe("network"); expect(errorAnalyzer.analyze({ status: 404, message: "Model not found" }).category).toBe("invalid-model"); expect(errorAnalyzer.analyze({ message: "context length exceeded" }).category).toBe("context-length"); expect(errorAnalyzer.analyze({ streaming: true, message: "stream reset" }).category).toBe("streaming"); });
  it("retains retry-after without leaking authorization or secret headers in reports", () => { const error = errorAnalyzer.analyze({ status: 429, message: "Bearer demo-token-must-not-appear", headers: { Authorization: "Bearer demo-token-must-not-appear", Cookie: "private", "Retry-After": "12" } }); const report = diagnosticReport({ id: "diagnostic-test", createdAt: "2026-01-01T00:00:00.000Z", source: "playground", category: error.category, title: error.title, status: "failed", retryable: error.retryable, error, context: { providerName: "Example", model: "test-model", headers: { Authorization: "Bearer demo-token-must-not-appear", "Retry-After": "12" } } }); const serialized = JSON.stringify(report); expect(report.technicalDetails.headers).toMatchObject({ Authorization: "[redacted]", "Retry-After": "12" }); expect(serialized).not.toContain("demo-token-must-not-appear"); expect(safeDiagnosticHeaders({ "Set-Cookie": "secret" })["Set-Cookie"]).toBe("[redacted]"); });
});
