import { beforeEach, describe, expect, it } from "vitest";
import { IndexedDbPromptRepository, IndexedDbProviderRepository, IndexedDbRequestRepository, IndexedDbSecretRepository, openLocalDatabase } from "@/storage/indexedDb";
import type { ProviderConfig, RequestRecord, SavedPrompt } from "@/domain/types";

const provider: ProviderConfig = { id: "provider-local", kind: "custom", name: "Local", baseUrl: "https://api.example.com/v1", apiKeyRef: "local:provider-local", defaultModel: "test-model", headers: {}, enabled: true, status: "unverified", createdAt: "2026-01-01T00:00:00.000Z", updatedAt: "2026-01-01T00:00:00.000Z" };
const record: RequestRecord = { id: "record-local", request: { id: "request-local", providerId: provider.id, model: "test-model", messages: [{ id: "m1", role: "user", content: "hello" }], stream: false, createdAt: "2026-01-01T00:00:00.000Z" }, status: "completed", providerName: "Local", model: "test-model", metrics: { startedAt: "2026-01-01T00:00:00.000Z", latencyMs: 12 }, createdAt: "2026-01-01T00:00:00.000Z" };

const prompt: SavedPrompt = { id: "prompt-local", name: "Local prompt", description: "A local recipe", messages: record.request.messages, tags: ["test"], createdAt: "2026-01-01T00:00:00.000Z", updatedAt: "2026-01-01T00:00:00.000Z" };
async function clearDatabase() { const database = await openLocalDatabase(); await new Promise<void>((resolve, reject) => { const transaction = database.transaction(["providers", "requests", "prompts", "secrets", "keys", "settings"], "readwrite"); ["providers", "requests", "prompts", "secrets", "keys", "settings"].forEach((name) => transaction.objectStore(name).clear()); transaction.oncomplete = () => resolve(); transaction.onerror = () => reject(transaction.error); }); database.close(); }
beforeEach(async () => { await clearDatabase(); });

describe("IndexedDB local-first repositories", () => {
  it("stores Provider metadata without a key and encrypts the secret at rest", async () => { const providers = new IndexedDbProviderRepository(); const secrets = new IndexedDbSecretRepository(); await providers.save(provider); await secrets.setSecret(provider.apiKeyRef, "YOUR_API_KEY"); expect(await providers.get(provider.id)).toEqual(provider); expect(await secrets.getSecret(provider.apiKeyRef)).toBe("YOUR_API_KEY"); expect(await secrets.hasSecret(provider.apiKeyRef)).toBe(true); const database = await openLocalDatabase(); const rawSecret = await new Promise<unknown>((resolve, reject) => { const transaction = database.transaction("secrets", "readonly"); const query = transaction.objectStore("secrets").get(provider.apiKeyRef); query.onsuccess = () => resolve(query.result); query.onerror = () => reject(query.error); }); database.close(); expect(JSON.stringify(rawSecret)).not.toContain("YOUR_API_KEY"); await secrets.deleteSecret(provider.apiKeyRef); expect(await secrets.hasSecret(provider.apiKeyRef)).toBe(false); await secrets.setSecret("local:second", "YOUR_API_KEY"); await secrets.clearSecrets(); expect(await secrets.hasSecret("local:second")).toBe(false); });
  it("implements request save, read, search, remove and clear locally", async () => { const requests = new IndexedDbRequestRepository(); await requests.save(record); expect((await requests.list())).toHaveLength(1); expect(await requests.get(record.id)).toEqual(record); expect((await requests.search("test-model"))).toHaveLength(1); await requests.remove(record.id); expect(await requests.list()).toEqual([]); await requests.save(record); await requests.clear(); expect(await requests.list()).toEqual([]); });
  it("stores saved prompts locally without credentials", async () => { const prompts = new IndexedDbPromptRepository(); await prompts.save(prompt); expect(await prompts.get(prompt.id)).toEqual(prompt); expect(await prompts.list()).toEqual([prompt]); await prompts.remove(prompt.id); expect(await prompts.list()).toEqual([]); await prompts.save(prompt); await prompts.clear(); expect(await prompts.list()).toEqual([]); });
});
