/** 精密工作台风格契约：Dashboard 是本地工作台首页，只呈现实际本地状态，不伪造请求指标。 */
import { Activity, ArrowRight, Braces, FileClock, PlugZap, Plus, ShieldCheck } from "lucide-react";
import { Link } from "wouter";
import { Button } from "@/components/ui/button";
import { EmptyState, MetricCard, PanelHeading, SignalTrace, StatusIndicator } from "@/components/ToolPrimitives";
import { useAppStore } from "@/store/useAppStore";

export default function Dashboard() {
  const { providers, records, setProviderDialogOpen } = useAppStore();
  const success = records.filter((record) => record.status === "completed").length;
  return <div className="page-canvas">
    <section className="page-header"><div><p className="eyebrow">Local workspace</p><h2>Request operations, at a glance.</h2><p>OpenAPI Playground keeps workspace state in this browser. Requests go directly to your selected Provider, not through an OpenAPI Playground proxy.</p></div><Button onClick={() => setProviderDialogOpen(true)}><Plus className="h-4 w-4" /> Add provider</Button></section>
    <section className="grid gap-3 md:grid-cols-2 xl:grid-cols-4"><MetricCard label="Requests today" value={String(records.length)} meta={records.length ? "Local request records" : "No requests yet"} icon={<Activity className="h-4 w-4" />} /><MetricCard label="Successful requests" value={String(success)} meta={success ? "Completed locally tracked requests" : "No successful requests yet"} icon={<ShieldCheck className="h-4 w-4" />} /><MetricCard label="Configured providers" value={String(providers.length)} meta={providers.length ? "Stored in local workspace" : "No providers configured"} icon={<PlugZap className="h-4 w-4" />} /><MetricCard label="Estimated cost" value="—" meta="Available when pricing is known" icon={<Braces className="h-4 w-4" />} /></section>
    <section className="mt-5 grid gap-5 xl:grid-cols-[1.12fr_.88fr]"><div className="panel"><PanelHeading eyebrow="Quick start" title="Set up the workspace" /><div className="px-4 pt-3"><SignalTrace labels={["Provider", "Request", "Inspect"]} active={providers.length ? 1 : 0} caption="Workspace trajectory" /></div><div className="divide-y divide-border">{[["01", "Add a provider", "Keep credentials local and begin with a saved connection.", "Add provider", () => setProviderDialogOpen(true)], ["02", "Prepare a request", "Choose a model, set parameters, and write a message.", "Open Playground", undefined], ["03", "Inspect the signal", "Check response, metrics, JSON, errors, and portable code.", "View workflow", undefined]].map(([index, title, detail, action, click]) => <div className="flex items-center gap-4 px-4 py-4" key={title as string}><span className="grid h-7 w-7 shrink-0 place-items-center rounded-md border border-border font-mono text-[11px] text-muted-foreground">{index as string}</span><div className="min-w-0 flex-1"><h3 className="text-[13px] font-semibold">{title as string}</h3><p className="mt-0.5 text-[12px] text-muted-foreground">{detail as string}</p></div>{click ? <Button size="sm" variant="outline" onClick={click as () => void}>{action as string}<ArrowRight className="h-3.5 w-3.5" /></Button> : <Link href="/playground"><Button size="sm" variant="outline">{action as string}<ArrowRight className="h-3.5 w-3.5" /></Button></Link>}</div>)}</div></div>
      <div className="panel"><PanelHeading eyebrow="Provider status" title="Local connections" action={<Link href="/providers" className="text-[12px] font-medium text-primary">Manage</Link>} />{providers.length ? <div className="divide-y divide-border">{providers.slice(0, 4).map((provider) => <div className="flex items-center gap-3 px-4 py-3" key={provider.id}><div className="grid h-8 w-8 place-items-center rounded-md bg-muted font-mono text-[11px] font-semibold">{provider.name.slice(0, 2).toUpperCase()}</div><div className="min-w-0 flex-1"><p className="truncate text-[13px] font-semibold">{provider.name}</p><p className="truncate font-mono text-[10px] text-muted-foreground">{provider.defaultModel || "No default model"}</p></div><StatusIndicator status={provider.status === "ready" ? "idle" : "invalid-configuration"} compact /></div>)}</div> : <EmptyState title="No providers configured" description="Add your first local provider before sending a request." action={<Button size="sm" onClick={() => setProviderDialogOpen(true)}><Plus className="h-3.5 w-3.5" /> Add provider</Button>} />}</div></section>
    <section className="mt-5 grid gap-5 xl:grid-cols-[1.12fr_.88fr]"><div className="panel"><PanelHeading eyebrow="Recent requests" title="Request history" action={<Link href="/history" className="text-[12px] font-medium text-primary">View history</Link>} />{records.length ? <div className="divide-y divide-border">{records.slice(0, 5).map((record) => <div className="flex items-center gap-3 px-4 py-3" key={record.id}><StatusIndicator status={record.status} compact /><div className="min-w-0 flex-1"><p className="truncate text-[12px] font-semibold">{record.model}</p><p className="text-[11px] text-muted-foreground">{record.isDemo ? "Local sample state" : record.providerName}</p></div><span className="font-mono text-[11px] text-muted-foreground">{new Date(record.createdAt).toLocaleTimeString([], { hour: "2-digit", minute: "2-digit" })}</span></div>)}</div> : <EmptyState icon={<FileClock className="h-5 w-5" />} title="No requests yet" description="Send a request to add a locally stored, clearly labeled record here." />}</div>
      <div className="rounded-lg border border-primary/20 bg-accent/45 p-4"><div className="flex gap-3"><ShieldCheck className="mt-0.5 h-5 w-5 shrink-0 text-primary" /><div><p className="text-[12px] font-semibold">Privacy boundary</p><p className="mt-1 text-[12px] leading-5 text-muted-foreground">Credentials are encrypted and stored locally. When you send a request, the key travels directly from this browser to your selected Provider—not to OpenAPI Playground.</p><Link href="/settings"><Button variant="link" size="sm" className="mt-2 h-auto px-0 text-primary">Review local data settings <ArrowRight className="h-3.5 w-3.5" /></Button></Link></div></div></div></section>
  </div>;
}
