/** 精密工作台风格契约：Diagnostics 以可操作的错误事实、状态轨迹和脱敏技术细节服务调试；不使用评分或复杂图表。 */
import { ClipboardCopy, Download, ExternalLink, Filter, RotateCcw, Search, Trash2 } from "lucide-react";
import { useEffect, useMemo, useState } from "react";
import { useLocation } from "wouter";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { PanelHeading, SignalTrace, StatusIndicator } from "@/components/ToolPrimitives";
import type { DiagnosticRecord } from "@/domain/diagnostics";
import { diagnosticReport } from "@/domain/diagnostics";
import { diagnosticsRepository } from "@/storage/indexedDb";
import { listDiagnostics, providerHealth } from "@/services/diagnosticsService";
import { useAppStore } from "@/store/useAppStore";

const copy = (value: string) => void navigator.clipboard?.writeText(value);
const download = (name: string, content: string, type: string) => { const url = URL.createObjectURL(new Blob([content], { type })); const anchor = document.createElement("a"); anchor.href = url; anchor.download = name; anchor.click(); URL.revokeObjectURL(url); };
const markdown = (record: DiagnosticRecord) => { const report = diagnosticReport(record); return `# ${report.title}\n\n| Field | Value |\n|---|---|\n| Category | ${report.category} |\n| Status | ${report.httpStatus} |\n| Provider | ${report.provider} |\n| Model | ${report.model} |\n| Retryable | ${report.retryable ? "Yes" : "No"} |\n\n## What happened\n${report.whatHappened}\n\n## Possible causes\n${report.possibleCauses.map((item) => `- ${item}`).join("\n")}\n\n## Recommended actions\n${report.recommendedActions.map((item) => `- ${item}`).join("\n")}\n\n## Technical details\n\`\`\`json\n${JSON.stringify(report.technicalDetails, null, 2)}\n\`\`\``; };
const guide = ["authentication", "rate-limit", "cors", "timeout", "invalid-model", "context-length", "streaming"];
export default function Diagnostics() {
  const { providers } = useAppStore(); const [, setLocation] = useLocation(); const [records, setRecords] = useState<DiagnosticRecord[]>([]); const [query, setQuery] = useState(""); const [category, setCategory] = useState("all"); const [provider, setProvider] = useState("all"); const [status, setStatus] = useState("all"); const [selectedId, setSelectedId] = useState<string>(); const [health, setHealth] = useState<Awaited<ReturnType<typeof providerHealth>>>([]);
  const refresh = async () => { const [next, nextHealth] = await Promise.all([listDiagnostics(), providerHealth(providers)]); setRecords(next); setHealth(nextHealth); if (!selectedId && next[0]) setSelectedId(next[0].id); };
  useEffect(() => { void refresh(); }, [providers.length]);
  const filtered = useMemo(() => records.filter((record) => { const text = `${record.title} ${record.category} ${record.context.providerName || ""} ${record.context.model || ""}`.toLowerCase(); return (!query || text.includes(query.toLowerCase())) && (category === "all" || record.category === category) && (provider === "all" || record.context.providerId === provider) && (status === "all" || record.status === status); }), [records, query, category, provider, status]); const selected = records.find((record) => record.id === selectedId) || filtered[0];
  const openSource = (record: DiagnosticRecord) => setLocation(record.source === "compare" ? "/compare" : record.source === "provider-test" ? "/providers" : "/playground"); const clear = async () => { await diagnosticsRepository.clear(); setRecords([]); setSelectedId(undefined); };
  return <div className="page-canvas diagnostics-workbench"><section className="page-header"><div><p className="eyebrow">Local fault analysis</p><h2>Developer Diagnostics</h2><p>Understand API failures, network issues, and provider configuration problems from safe local records.</p></div><div className="flex gap-2"><Button variant="outline" onClick={() => void refresh()}><RotateCcw className="h-4 w-4" /> Refresh</Button><Button variant="outline" onClick={() => void clear()} disabled={!records.length}><Trash2 className="h-4 w-4" /> Clear history</Button></div></section>
    <section className="diagnostic-overview"><article className="panel"><PanelHeading eyebrow="Recent errors" title={`${records.length} local record${records.length === 1 ? "" : "s"}`} /><div className="metric-rail"><span>Failed</span><strong>{records.filter((record) => record.status === "failed").length}</strong><span>Retryable</span><strong>{records.filter((record) => record.retryable).length}</strong></div></article><article className="panel"><PanelHeading eyebrow="Error categories" title={`${new Set(records.map((record) => record.category)).size} observed`} /><div className="category-readout">{records.length ? Array.from(new Set(records.map((record) => record.category))).slice(0, 5).map((item) => <span key={item}>{item}</span>) : <span>No errors recorded</span>}</div></article><article className="panel"><PanelHeading eyebrow="Provider health" title="Manual checks only" /><div className="health-readout">{health.length ? health.map((item) => <span key={item.providerId}><i className={`health-dot health-${item.status}`} />{item.providerName}<small>{item.latencyMs ? `${item.latencyMs} ms` : item.lastCheckedAt ? "Checked" : "Unknown"}</small></span>) : <span>No providers stored</span>}</div></article></section>
    <section className="panel diagnostics-console"><PanelHeading eyebrow="Diagnostics history" title="Find a recorded failure" /><div className="diagnostic-trajectory"><SignalTrace labels={["Request", "Failure", "Cause", "Action"]} active={selected ? 3 : 0} caption="Diagnostic trajectory" /></div><div className="diagnostic-filters"><label><Search className="h-3.5 w-3.5" /><Input aria-label="Search diagnostics" value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search title, provider, model…" /></label><select aria-label="Filter diagnostics category" value={category} onChange={(event) => setCategory(event.target.value)}><option value="all">All categories</option>{Array.from(new Set(records.map((record) => record.category))).map((item) => <option key={item} value={item}>{item}</option>)}</select><select aria-label="Filter diagnostics provider" value={provider} onChange={(event) => setProvider(event.target.value)}><option value="all">All providers</option>{providers.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select><select aria-label="Filter diagnostics status" value={status} onChange={(event) => setStatus(event.target.value)}><option value="all">All statuses</option><option value="failed">Failed</option><option value="aborted">Aborted</option><option value="warning">Warning</option></select><Filter className="h-4 w-4 text-muted-foreground" /></div><div className="diagnostic-split"><div className="diagnostic-list" role="list">{filtered.length ? filtered.map((record) => <button type="button" role="listitem" key={record.id} className={record.id === selected?.id ? "diagnostic-row is-selected" : "diagnostic-row"} onClick={() => setSelectedId(record.id)}><StatusIndicator status={record.status === "failed" ? "failed" : "idle"} compact /><span><strong>{record.title}</strong><small>{record.context.providerName || "Provider"} · {record.context.model || "N/A"} · {new Date(record.createdAt).toLocaleString()}</small></span><code>{record.error.status || "N/A"}</code></button>) : <div className="local-empty-rail">No local diagnostic records match these filters.</div>}</div>{selected ? <DiagnosticDetail record={selected} onCopy={() => copy(JSON.stringify(diagnosticReport(selected), null, 2))} onExport={(format) => { const report = diagnosticReport(selected); download(`diagnostic-${selected.id}.${format === "markdown" ? "md" : format}`, format === "markdown" ? markdown(selected) : format === "txt" ? markdown(selected) : JSON.stringify(report, null, 2), format === "json" ? "application/json" : "text/plain"); }} onSource={() => openSource(selected)} /> : <DiagnosticEmpty />}</div></section>
    <section className="panel troubleshooting"><PanelHeading eyebrow="Troubleshooting" title="Local diagnostic guides" /><div className="troubleshooting-grid">{guide.map((item) => <article key={item}><p className="eyebrow">{item}</p><strong>{guideTitle(item)}</strong><p>Review the recorded causes and use the linked source workflow to verify configuration, request shape, or provider reachability.</p></article>)}</div></section>
  </div>;
}
function DiagnosticDetail({ record, onCopy, onExport, onSource }: { record: DiagnosticRecord; onCopy: () => void; onExport: (format: "json" | "txt" | "markdown") => void; onSource: () => void }) { const report = diagnosticReport(record); return <article className="diagnostic-detail"><header><div><p className="eyebrow">{record.category}</p><h3>{record.title}</h3></div><StatusIndicator status="failed" compact /></header><div className="detail-facts"><span>HTTP <strong>{report.httpStatus}</strong></span><span>Provider <strong>{report.provider}</strong></span><span>Model <strong>{report.model}</strong></span><span>Retryable <strong>{report.retryable ? "Yes" : "No"}</strong></span><span>Timestamp <strong>{new Date(record.createdAt).toLocaleString()}</strong></span></div><DetailSection title="What happened"><p>{report.whatHappened}</p></DetailSection><DetailSection title="Possible causes"><ul>{report.possibleCauses.map((item) => <li key={item}>{item}</li>)}</ul></DetailSection><DetailSection title="Recommended actions"><ul>{report.recommendedActions.map((item) => <li key={item}>{item}</li>)}</ul></DetailSection><DetailSection title="Technical details"><pre>{JSON.stringify(report.technicalDetails, null, 2)}</pre></DetailSection><footer>{record.retryable && <Button size="sm" variant="outline" onClick={onSource}><ExternalLink className="h-3.5 w-3.5" /> Open source to retry</Button>}<Button size="sm" variant="outline" onClick={onCopy}><ClipboardCopy className="h-3.5 w-3.5" /> Copy report</Button><Button size="sm" variant="ghost" onClick={() => onExport("json")}><Download className="h-3.5 w-3.5" /> JSON</Button><Button size="sm" variant="ghost" onClick={() => onExport("markdown")}>Markdown</Button></footer></article>; }
function DiagnosticEmpty() { return <div className="diagnostic-detail empty-detail"><p className="eyebrow">Inspection slots</p><div className="diagnostic-empty-slots"><span>01 · Failure source<strong>Provider / request context</strong></span><span>02 · Cause<strong>Normalized error category</strong></span><span>03 · Evidence<strong>HTTP, safe headers, response code</strong></span><span>04 · Action<strong>Retry or configuration check</strong></span><span>05 · Raw details<strong>Sanitized technical payload</strong></span><span>06 · Lifecycle<strong>Request → failure → diagnosis</strong></span></div><small>Select a local diagnostic record to populate this inspection tray.</small></div>; }
function DetailSection({ title, children }: { title: string; children: React.ReactNode }) { return <section><p className="eyebrow">{title}</p>{children}</section>; } function guideTitle(category: string) { return ({ authentication: "Authentication", "rate-limit": "Rate limits", cors: "CORS", timeout: "Timeout", "invalid-model": "Invalid model", "context-length": "Context length", streaming: "Streaming" } as Record<string, string>)[category] || category; }
