/** 精密工作台风格契约：文档以真实信息架构和任务导向结构说明已实现能力、兼容性边界与本地安全约束。 */
import { BookOpenCheck, ChevronRight, CircleHelp, Code2, Keyboard, LockKeyhole, PlugZap, TriangleAlert } from "lucide-react";
import { Link } from "wouter";

const sections = [
  ["Quick Start", "Configure a local provider, select a model, send a request, then inspect the response and local history.", BookOpenCheck, "/providers"], ["Provider Guide", "Use OpenAI-compatible endpoints with your own credentials, test GET /models, and select or enter a model ID.", PlugZap, "/providers"], ["Error Codes", "Review safe, action-oriented diagnostics for HTTP, authentication, rate-limit, network, CORS, model, context, and streaming failures.", TriangleAlert, "/diagnostics"], ["Privacy", "Understand local encrypted credential storage, browser-direct requests, safe exports, and the limits of browser security.", LockKeyhole, "/settings"], ["Keyboard Shortcuts", "Open the command menu with Ctrl/⌘ K and send a prepared request with Ctrl/⌘ Enter.", Keyboard, "/settings"], ["Contributing", "Keep changes focused, run the validation suite, and preserve domain, storage, and Provider boundaries.", Code2, "/settings"], ["FAQ", "Review scope, compatibility, local data, and Provider CORS considerations before sharing a configuration.", CircleHelp, "/settings"],
];

export default function Docs() { return <div className="page-canvas"><section className="page-header"><div><p className="eyebrow">Workspace guide</p><h2>Build, inspect, and diagnose locally.</h2><p>Use this guide to move from local Provider setup to request inspection, model comparison, and safe diagnostics without routing credentials through a shared proxy.</p></div></section><div className="docs-layout"><aside className="docs-nav"><p>GETTING STARTED</p><a href="#quick-start" className="active">Quick Start</a><a href="#provider-guide">Provider Guide</a><a href="#error-codes">Error Codes</a><p>PROJECT</p><a href="#privacy">Privacy</a><a href="#keyboard-shortcuts">Keyboard Shortcuts</a><a href="#contributing">Contributing</a><a href="#faq">FAQ</a></aside><main className="docs-content"><div className="rounded-lg border border-primary/20 bg-accent/35 p-4"><p className="eyebrow">Local-first boundary</p><h3 className="text-base font-semibold">Your selected Provider receives the request—not OpenAPI Playground.</h3><p className="mt-2 text-[13px] leading-5 text-muted-foreground">Credentials are encrypted and stored locally. Compatible endpoint behavior and CORS support can vary, so test each Provider and model in your own environment.</p></div><div className="mt-5 space-y-3">{sections.map(([title, description, Icon, href]) => { const SectionIcon = Icon as typeof BookOpenCheck; return <section id={(title as string).toLowerCase().replaceAll(" ", "-")} className="doc-section" key={title as string}><SectionIcon className="h-4 w-4 text-primary" /><div><h3>{title as string}</h3><p>{description as string}</p><Link href={href as string}><span className="doc-link">Open related workspace <ChevronRight className="h-3.5 w-3.5" /></span></Link></div></section>; })}</div></main></div></div>; }
