/** 精密工作台风格契约：设置页直接呈现隐私、数据保留与导入导出边界，不暗藏远端同步或凭据传输。 */
import { AlertTriangle, Download, FileWarning, ShieldCheck, SunMoon, Trash2, Upload } from "lucide-react";
import { useRef, useState } from "react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Slider } from "@/components/ui/slider";
import { Switch } from "@/components/ui/switch";
import { PanelHeading } from "@/components/ToolPrimitives";
import { useAppStore } from "@/store/useAppStore";

export default function Settings() {
  const { providers, settings, updateSettings, exportWorkspace, importWorkspace, clearLocalWorkspace } = useAppStore(); const input = useRef<HTMLInputElement>(null); const [workspaceMessage, setWorkspaceMessage] = useState("");
  const exportLocalWorkspace = () => { const snapshot = exportWorkspace(); const blob = new Blob([JSON.stringify(snapshot, null, 2)], { type: "application/json" }); const url = URL.createObjectURL(blob); const link = document.createElement("a"); link.href = url; link.download = `openapi-playground-workspace-${new Date().toISOString().slice(0, 10)}.json`; link.click(); URL.revokeObjectURL(url); setWorkspaceMessage("Workspace exported without API keys, secrets, or Authorization headers."); };
  const importLocalWorkspace = async (file?: File) => { if (!file) return; try { const result = await importWorkspace(JSON.parse(await file.text())); setWorkspaceMessage(`Imported ${result.importedProviders} provider metadata record(s), ${result.importedPrompts} prompt(s), and ${result.importedHistory} history record(s). Imported Providers are unverified and require a new local API key.`); } catch (error) { setWorkspaceMessage(error instanceof Error ? error.message : "Workspace import failed."); } finally { if (input.current) input.current.value = ""; } };
  return <div className="page-canvas"><section className="page-header"><div><p className="eyebrow">Local preferences</p><h2>Settings and data boundaries.</h2><p>Preferences, Provider metadata, encrypted keys, prompts, and request records stay in this browser. No account, analytics profile, or cloud workspace is created.</p></div></section><div className="settings-grid">
    <section className="panel"><PanelHeading eyebrow="Appearance" title="Theme" /><div className="panel-body space-y-4"><div className="field"><Label>Color mode</Label><Select value={settings.theme} onValueChange={(value) => void updateSettings({ theme: value as typeof settings.theme })}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent><SelectItem value="light">Light</SelectItem><SelectItem value="dark">Dark</SelectItem><SelectItem value="system">System</SelectItem></SelectContent></Select></div><div className="rounded-md border border-border bg-muted/35 p-3"><div className="flex gap-2"><SunMoon className="h-4 w-4 text-primary" /><p className="text-[12px] leading-5 text-muted-foreground">Use the sidebar toggle for a fast theme change. System mode follows the browser preference after reload.</p></div></div></div></section>
    <section className="panel"><PanelHeading eyebrow="Request defaults" title="New request settings" /><div className="panel-body space-y-4"><div className="field"><Label>Default Provider</Label><select className="native-select" value={settings.defaultProviderId || "none"} onChange={(event) => void updateSettings({ defaultProviderId: event.target.value === "none" ? undefined : event.target.value })}><option value="none">Choose after adding a provider</option>{providers.filter((provider) => provider.enabled).map((provider) => <option key={provider.id} value={provider.id}>{provider.name}</option>)}</select></div><div className="field"><Label>Default model</Label><Input value={settings.defaultModel || ""} onChange={(event) => void updateSettings({ defaultModel: event.target.value })} placeholder="Enter a default model ID" /></div><div className="field"><div className="flex justify-between"><Label>Default temperature</Label><span className="font-mono text-[11px] text-muted-foreground">{settings.defaultTemperature.toFixed(1)}</span></div><Slider value={[settings.defaultTemperature]} onValueChange={([value]) => void updateSettings({ defaultTemperature: value })} min={0} max={2} step={0.1} /></div><div className="field"><Label>Default max tokens</Label><Input value={String(settings.defaultMaxTokens)} onChange={(event) => void updateSettings({ defaultMaxTokens: Number(event.target.value) || 0 })} inputMode="numeric" /></div></div></section>
    <section className="panel"><PanelHeading eyebrow="Local storage" title="Retention & workspace" /><div className="panel-body space-y-4"><div className="field-grid"><div className="field"><Label>History retention</Label><Select value={settings.historyRetention} onValueChange={(value) => void updateSettings({ historyRetention: value as typeof settings.historyRetention })}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent><SelectItem value="7d">7 days</SelectItem><SelectItem value="30d">30 days</SelectItem><SelectItem value="90d">90 days</SelectItem><SelectItem value="forever">Until manually cleared</SelectItem></SelectContent></Select></div><div className="field"><Label>Prompt retention</Label><Select value={settings.promptRetention} onValueChange={(value) => void updateSettings({ promptRetention: value as typeof settings.promptRetention })}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent><SelectItem value="30d">30 days</SelectItem><SelectItem value="90d">90 days</SelectItem><SelectItem value="forever">Until manually cleared</SelectItem></SelectContent></Select></div></div><input ref={input} className="hidden" type="file" accept="application/json" aria-label="Import local workspace file" onChange={(event) => void importLocalWorkspace(event.target.files?.[0])} /><div className="grid grid-cols-2 gap-2"><Button variant="outline" size="sm" onClick={() => input.current?.click()}><Upload className="h-3.5 w-3.5" /> Import</Button><Button variant="outline" size="sm" onClick={exportLocalWorkspace}><Download className="h-3.5 w-3.5" /> Export</Button></div><div className="rounded-md border border-primary/20 bg-accent/35 p-3 text-[11px] leading-4 text-muted-foreground"><FileWarning className="mr-1 inline h-3.5 w-3.5 text-primary" /> Export includes Provider metadata, saved prompts, history, and settings only. Secrets, API keys, and Authorization headers are always excluded.</div>{workspaceMessage && <p role="status" className="text-[11px] leading-4 text-muted-foreground">{workspaceMessage}</p>}</div></section>
    <section className="panel"><PanelHeading eyebrow="Network boundary" title="Privacy & proxy" /><div className="panel-body space-y-4"><div className="flex items-start justify-between gap-4 rounded-md border border-primary/20 bg-accent/40 p-3"><div className="flex gap-2"><ShieldCheck className="mt-0.5 h-4 w-4 shrink-0 text-primary" /><p className="text-[12px] leading-5 text-muted-foreground"><strong className="text-foreground">Direct browser mode.</strong> Browser → Provider remains the active route. CORS errors are diagnosed, not silently forwarded through a universal cloud proxy.</p></div><Switch checked={false} disabled aria-label="Self-hosted proxy unavailable" /></div><p className="text-[11px] leading-4 text-muted-foreground">A self-hosted proxy is a future extension point only; no proxy server exists in this workspace.</p></div></section>
  </div><section id="shortcuts" className="panel mt-5"><PanelHeading eyebrow="Keyboard" title="Shortcut help" /><div className="shortcut-grid p-4">{[["⌘ / Ctrl + Enter", "Send active request"], ["Esc", "Stop request or exit fullscreen"], ["⌘ / Ctrl + K", "Open command menu"]].map(([key, label]) => <div key={key}><kbd>{key}</kbd><span>{label}</span></div>)}</div></section><section className="panel danger-zone mt-5"><PanelHeading eyebrow="Danger zone" title="Clear all local workspace data" /><div className="flex flex-wrap items-center justify-between gap-4 p-4"><div className="flex max-w-xl gap-3"><AlertTriangle className="mt-0.5 h-5 w-5 shrink-0 text-destructive" /><p className="text-[12px] leading-5 text-muted-foreground">This removes local Provider metadata, encrypted secrets, saved prompts, and request history. This cannot be undone and does not affect any external Provider account.</p></div><Button variant="destructive" onClick={() => { if (window.confirm("Clear all local workspace data, including encrypted keys, prompts, and request history? This cannot be undone.")) void clearLocalWorkspace(); }}><Trash2 className="h-4 w-4" /> Clear local data</Button></div></section></div>;
}
