/** 精密工作台风格契约：错误规则只消费已脱敏的状态与消息，向用户提供可行动的诊断而不回显凭据、Cookie 或原始敏感头。 */
import type { ErrorCategory, ProviderError } from "./types";
import { safeDiagnosticHeaders, sanitizeText } from "./diagnostics";

export interface ErrorAnalyzerInput { status?: number; message?: string; aborted?: boolean; malformed?: boolean; streaming?: boolean; headers?: Record<string, string>; code?: string; param?: string; endpoint?: string; }
export interface ErrorRule { category: ErrorCategory; matches: (input: ErrorAnalyzerInput, lower: string) => boolean; build: (input: ErrorAnalyzerInput, lower: string) => ProviderError; }
export interface ErrorAnalyzer { analyze(input: ErrorAnalyzerInput): ProviderError; }

const makeError = (category: ErrorCategory, title: string, description: string, retryable: boolean, causes: string[], actions: string[], input: ErrorAnalyzerInput): ProviderError => ({ category, title, description, message: sanitizeText(input.message || description), status: input.status, providerCode: sanitizeText(input.code), retryable, causes: causes.map(sanitizeText), actions: actions.map(sanitizeText), safeDetails: { responseCode: sanitizeText(input.code), parameter: sanitizeText(input.param), endpoint: sanitizeText(input.endpoint), retryAfter: input.headers?.["retry-after"] || input.headers?.["Retry-After"] || "N/A", headers: safeDiagnosticHeaders(input.headers) } });
const includesAny = (value: string, terms: string[]) => terms.some((term) => value.includes(term));
const rules: ErrorRule[] = [
  { category: "authentication", matches: (input) => input.status === 401, build: (input) => makeError("authentication", "Invalid API Key / Authentication", "The provider rejected the supplied credentials.", false, ["The API key may be invalid, expired, or belong to a different provider."], ["Check the masked API key and Base URL, then test the connection again."], input) },
  { category: "forbidden", matches: (input) => input.status === 403, build: (input) => makeError("forbidden", "Permission Denied", "The provider accepted the request but denied access.", false, ["The key, account, endpoint, or selected model may not have permission."], ["Check account permissions and verify that the selected model is enabled."], input) },
  { category: "invalid-model", matches: (input, lower) => (input.status === 404 || input.status === 400) && includesAny(lower, ["model", "deployment", "unsupported"]), build: (input) => makeError("invalid-model", "Invalid Model", "The selected model was not found or is unavailable for this Provider.", false, ["The model ID may be misspelled, unavailable, or restricted."], ["Use Model Discovery or enter the exact model ID supported by this Provider."], input) },
  { category: "not-found", matches: (input) => input.status === 404, build: (input) => makeError("not-found", "Provider Route Not Found", "The provider could not find the requested endpoint.", false, ["The Base URL may be incomplete or use an unsupported route."], ["Verify the Base URL path and confirm this endpoint is OpenAI-compatible."], input) },
  { category: "timeout", matches: (input, lower) => input.status === 408 || includesAny(lower, ["timeout", "timed out"]), build: (input) => makeError("timeout", "Request Timeout", "The provider did not finish the request in time.", true, ["The network, provider, or request payload may be slow."], ["Retry the request or reduce prompt size."], input) },
  { category: "conflict", matches: (input) => input.status === 409, build: (input) => makeError("conflict", "Request Conflict", "The provider reported a conflicting request state.", true, ["A provider-side operation may still be in progress."], ["Retry after a short pause."], input) },
  { category: "context-length", matches: (input, lower) => input.status === 413 || includesAny(lower, ["context length", "token limit", "prompt too long", "payload too large", "request too large"]), build: (input) => makeError("context-length", input.status === 413 ? "Request Too Large" : "Context Length Exceeded", "The request exceeds the selected model or endpoint limit.", false, ["The prompt, message history, or payload is too large."], ["Shorten the prompt, reduce attachments, or choose a model with a larger context window."], input) },
  { category: "rate-limit", matches: (input) => input.status === 429, build: (input) => makeError("rate-limit", "Rate Limit / Quota", "The provider temporarily rejected this request.", true, ["The account, model, or endpoint may have exceeded its current quota."], ["Retry after the documented provider interval or reduce concurrent requests."], input) },
  { category: "bad-request", matches: (input) => input.status === 400 || input.status === 422, build: (input) => makeError("bad-request", "Invalid Request", "The provider could not accept the request format or parameters.", false, ["A parameter may be unsupported, missing, malformed, or out of range."], ["Review model, message format, parameter names, and the safe technical details."], input) },
  { category: "server", matches: (input) => [500, 501, 502, 503, 504].includes(input.status || 0), build: (input) => makeError("server", ({ 500: "Internal Server Error", 501: "Not Implemented", 502: "Bad Gateway", 503: "Service Unavailable", 504: "Gateway Timeout" } as Record<number, string>)[input.status || 500], "The provider returned a server-side error.", true, ["The upstream service may be unavailable or overloaded."], ["Retry later and check the provider status page if available."], input) },
];

export class RuleBasedErrorAnalyzer implements ErrorAnalyzer {
  analyze(input: ErrorAnalyzerInput): ProviderError { const safeInput = { ...input, message: sanitizeText(input.message), headers: safeDiagnosticHeaders(input.headers) }; const lower = (safeInput.message || "").toLowerCase(); if (safeInput.aborted) return makeError("unknown", "Request Stopped", "The request was cancelled locally before completion.", false, [], ["Edit the request and send it again when ready."], safeInput); if (safeInput.malformed) return makeError("malformed-response", "Unexpected Provider Response", "The response could not be parsed as a compatible JSON payload.", false, ["The endpoint may not be OpenAI-compatible or may have returned an HTML error page."], ["Inspect the safe JSON panel and verify the Base URL."], safeInput); if (safeInput.streaming || includesAny(lower, ["sse", "stream interrupted", "stream termination", "stream reset"])) return makeError("streaming", "Streaming Error", "The provider stream ended before a complete response was received.", true, ["The connection may have been interrupted or the endpoint may not support this streaming format."], ["Retry the request or disable streaming to test the endpoint."], safeInput); if (includesAny(lower, ["cors", "cross-origin"])) return makeError("cors", "CORS Error", "The provider may not allow browser-based cross-origin requests.", false, ["The Provider CORS policy may block this browser request."], ["Verify the Base URL, check the provider CORS policy, or try a compatible endpoint. A self-hosted proxy is not included in this version."], safeInput); if (includesAny(lower, ["dns", "connection refused", "connection reset", "network unavailable", "failed to fetch", "networkerror"])) return makeError("network", "Network Request Failed", "The browser could not reach the provider endpoint.", true, ["The network, DNS, endpoint, or provider connection may be unavailable."], ["Verify the Base URL, network connection, and provider reachability before retrying."], safeInput); const rule = rules.find((candidate) => candidate.matches(safeInput, lower)); if (rule) return rule.build(safeInput, lower); return makeError("unknown", "Unknown Error", "The provider returned an unclassified error.", false, ["No matching error rule is available for this response."], ["Review the safe diagnostics and provider documentation."], safeInput); }
}
export const errorAnalyzer = new RuleBasedErrorAnalyzer();
