/** 精密工作台风格契约：Repository 层仅处理安全的本地工作数据；凭据独立加密且从不进入 Prompt、历史或比较快照。 */
import type { AppSettings, ProviderConfig, RequestRecord, SavedPrompt } from "./types";
import type { SavedComparison } from "./compare";
import type { DiagnosticRecord } from "./diagnostics";

export interface ProviderRepository { list(): Promise<ProviderConfig[]>; get(id: string): Promise<ProviderConfig | undefined>; save(provider: ProviderConfig): Promise<void>; remove(id: string): Promise<void>; }
export interface RequestRepository { list(): Promise<RequestRecord[]>; get(id: string): Promise<RequestRecord | undefined>; save(record: RequestRecord): Promise<void>; remove(id: string): Promise<void>; clear(): Promise<void>; search(query: string): Promise<RequestRecord[]>; }
export interface PromptRepository { list(): Promise<SavedPrompt[]>; get(id: string): Promise<SavedPrompt | undefined>; save(prompt: SavedPrompt): Promise<void>; remove(id: string): Promise<void>; clear(): Promise<void>; }
export interface ComparisonRepository { list(): Promise<SavedComparison[]>; get(id: string): Promise<SavedComparison | undefined>; save(comparison: SavedComparison): Promise<void>; remove(id: string): Promise<void>; clear(): Promise<void>; }
export interface DiagnosticsRepository { list(): Promise<DiagnosticRecord[]>; get(id: string): Promise<DiagnosticRecord | undefined>; save(record: DiagnosticRecord): Promise<void>; remove(id: string): Promise<void>; clear(): Promise<void>; }
export interface SettingsRepository { get(): Promise<AppSettings>; save(settings: AppSettings): Promise<void>; }
export interface SecretRepository { setSecret(ref: string, secret: string): Promise<void>; getSecret(ref: string): Promise<string | undefined>; deleteSecret(ref: string): Promise<void>; hasSecret(ref: string): Promise<boolean>; clearSecrets(): Promise<void>; }

export class InMemoryProviderRepository implements ProviderRepository { private records: ProviderConfig[] = []; async list() { return this.records.slice(); } async get(id: string) { return this.records.find((item) => item.id === id); } async save(provider: ProviderConfig) { this.records = this.records.filter((item) => item.id !== provider.id).concat(provider); } async remove(id: string) { this.records = this.records.filter((item) => item.id !== id); } }
export class InMemoryRequestRepository implements RequestRepository { private records: RequestRecord[] = []; async list() { return this.records.slice(); } async get(id: string) { return this.records.find((item) => item.id === id); } async save(record: RequestRecord) { this.records = [record].concat(this.records.filter((item) => item.id !== record.id)); } async remove(id: string) { this.records = this.records.filter((item) => item.id !== id); } async clear() { this.records = []; } async search(query: string) { const normalized = query.toLowerCase(); return this.records.filter((record) => `${record.providerName} ${record.model} ${record.status}`.toLowerCase().includes(normalized)); } }
export class InMemoryPromptRepository implements PromptRepository { private records: SavedPrompt[] = []; async list() { return this.records.slice(); } async get(id: string) { return this.records.find((item) => item.id === id); } async save(prompt: SavedPrompt) { this.records = [prompt].concat(this.records.filter((item) => item.id !== prompt.id)); } async remove(id: string) { this.records = this.records.filter((item) => item.id !== id); } async clear() { this.records = []; } }
export class InMemoryComparisonRepository implements ComparisonRepository { private records: SavedComparison[] = []; async list() { return this.records.slice(); } async get(id: string) { return this.records.find((item) => item.id === id); } async save(comparison: SavedComparison) { this.records = [comparison].concat(this.records.filter((item) => item.id !== comparison.id)); } async remove(id: string) { this.records = this.records.filter((item) => item.id !== id); } async clear() { this.records = []; } }
export class InMemoryDiagnosticsRepository implements DiagnosticsRepository { private records: DiagnosticRecord[] = []; async list() { return this.records.slice(); } async get(id: string) { return this.records.find((item) => item.id === id); } async save(record: DiagnosticRecord) { this.records = [record].concat(this.records.filter((item) => item.id !== record.id)); } async remove(id: string) { this.records = this.records.filter((item) => item.id !== id); } async clear() { this.records = []; } }
export class InMemorySettingsRepository implements SettingsRepository { private settings: AppSettings = { theme: "system", defaultTemperature: 0.7, defaultMaxTokens: 1024, historyRetention: "30d", promptRetention: "forever", proxyMode: "direct", demoMode: false, panelLayout: { configuration: 22, composer: 43, inspector: 35 } }; async get() { return { ...this.settings }; } async save(settings: AppSettings) { this.settings = { ...settings }; } }
export class InMemorySecretRepository implements SecretRepository { private secrets = new Map<string, string>(); async setSecret(ref: string, secret: string) { this.secrets.set(ref, secret); } async getSecret(ref: string) { return this.secrets.get(ref); } async deleteSecret(ref: string) { this.secrets.delete(ref); } async hasSecret(ref: string) { return this.secrets.has(ref); } async clearSecrets() { this.secrets.clear(); } }
