/** 精密工作台风格契约：IndexedDB 分隔 Provider 元数据、Prompt、请求/比较历史、设置和加密密钥；所有导出数据均排除凭据。 */
import type { SavedComparison } from "@/domain/compare";
import type { DiagnosticRecord } from "@/domain/diagnostics";
import type { AppSettings, ProviderConfig, RequestRecord, SavedPrompt } from "@/domain/types";
import type { ComparisonRepository, DiagnosticsRepository, PromptRepository, ProviderRepository, RequestRepository, SecretRepository, SettingsRepository } from "@/domain/repositories";
import { createMasterKey, decryptSecret, encryptSecret, type EncryptedSecret } from "./crypto";

const DATABASE_NAME = "openapi-playground"; const DATABASE_VERSION = 4;
const PROVIDERS = "providers"; const REQUESTS = "requests"; const PROMPTS = "prompts"; const COMPARISONS = "comparisons"; const DIAGNOSTICS = "diagnostics"; const SECRETS = "secrets"; const KEYS = "keys"; const SETTINGS = "settings"; const MASTER_KEY = "local-master-key"; const SETTINGS_KEY = "app-settings";
let masterKeyCache: CryptoKey | undefined;
const defaultSettings: AppSettings = { theme: "system", defaultTemperature: 0.7, defaultMaxTokens: 1024, historyRetention: "30d", promptRetention: "forever", proxyMode: "direct", demoMode: false, panelLayout: { configuration: 22, composer: 43, inspector: 35 } };
const requestResult = <T>(request: IDBRequest<T>) => new Promise<T>((resolve, reject) => { request.onsuccess = () => resolve(request.result); request.onerror = () => reject(request.error || new Error("Local storage request failed.")); });
export function openLocalDatabase(): Promise<IDBDatabase> { return new Promise((resolve, reject) => { const request = indexedDB.open(DATABASE_NAME, DATABASE_VERSION); request.onupgradeneeded = () => { const database = request.result; if (!database.objectStoreNames.contains(PROVIDERS)) database.createObjectStore(PROVIDERS, { keyPath: "id" }); if (!database.objectStoreNames.contains(SECRETS)) database.createObjectStore(SECRETS, { keyPath: "ref" }); if (!database.objectStoreNames.contains(KEYS)) database.createObjectStore(KEYS, { keyPath: "id" }); if (!database.objectStoreNames.contains(SETTINGS)) database.createObjectStore(SETTINGS, { keyPath: "id" }); if (!database.objectStoreNames.contains(REQUESTS)) { const store = database.createObjectStore(REQUESTS, { keyPath: "id" }); store.createIndex("createdAt", "createdAt"); store.createIndex("providerId", "request.providerId"); store.createIndex("status", "status"); } if (!database.objectStoreNames.contains(PROMPTS)) { const store = database.createObjectStore(PROMPTS, { keyPath: "id" }); store.createIndex("updatedAt", "updatedAt"); store.createIndex("favorite", "favorite"); } if (!database.objectStoreNames.contains(COMPARISONS)) { const store = database.createObjectStore(COMPARISONS, { keyPath: "id" }); store.createIndex("createdAt", "createdAt"); store.createIndex("updatedAt", "updatedAt"); } if (!database.objectStoreNames.contains(DIAGNOSTICS)) { const store = database.createObjectStore(DIAGNOSTICS, { keyPath: "id" }); store.createIndex("createdAt", "createdAt"); store.createIndex("category", "category"); store.createIndex("providerId", "context.providerId"); } }; request.onsuccess = () => resolve(request.result); request.onerror = () => reject(request.error || new Error("Unable to open local storage.")); }); }
async function withStore<T>(storeName: string, mode: IDBTransactionMode, action: (store: IDBObjectStore) => IDBRequest<T>): Promise<T> { const database = await openLocalDatabase(); try { const transaction = database.transaction(storeName, mode); return await requestResult(action(transaction.objectStore(storeName))); } finally { database.close(); } }
async function localMasterKey(): Promise<CryptoKey> { if (masterKeyCache) return masterKeyCache; const existing = await withStore<CryptoKey | undefined>(KEYS, "readonly", (store) => store.get(MASTER_KEY)); if (existing && typeof existing === "object" && "type" in existing && "algorithm" in existing) { masterKeyCache = existing; return existing; } const key = await createMasterKey(); masterKeyCache = key; await withStore(KEYS, "readwrite", (store) => store.put({ id: MASTER_KEY, key })); return key; }
export class IndexedDbProviderRepository implements ProviderRepository { async list() { const records = await withStore<ProviderConfig[]>(PROVIDERS, "readonly", (store) => store.getAll()); return records.sort((left, right) => right.updatedAt.localeCompare(left.updatedAt)); } async get(id: string) { return withStore<ProviderConfig | undefined>(PROVIDERS, "readonly", (store) => store.get(id)); } async save(provider: ProviderConfig) { await withStore(PROVIDERS, "readwrite", (store) => store.put({ ...provider, headers: provider.headers || {} })); } async remove(id: string) { await withStore(PROVIDERS, "readwrite", (store) => store.delete(id)); } }
export class IndexedDbRequestRepository implements RequestRepository { async list() { const records = await withStore<RequestRecord[]>(REQUESTS, "readonly", (store) => store.getAll()); return records.sort((left, right) => right.createdAt.localeCompare(left.createdAt)); } async get(id: string) { return withStore<RequestRecord | undefined>(REQUESTS, "readonly", (store) => store.get(id)); } async save(record: RequestRecord) { await withStore(REQUESTS, "readwrite", (store) => store.put(record)); } async remove(id: string) { await withStore(REQUESTS, "readwrite", (store) => store.delete(id)); } async clear() { await withStore(REQUESTS, "readwrite", (store) => store.clear()); } async search(query: string) { const normalized = query.trim().toLowerCase(); const records = await this.list(); return !normalized ? records : records.filter((record) => `${record.providerName} ${record.model} ${record.status} ${record.request.messages.map((message) => message.content).join(" ")}`.toLowerCase().includes(normalized)); } }
export class IndexedDbPromptRepository implements PromptRepository { async list() { const prompts = await withStore<SavedPrompt[]>(PROMPTS, "readonly", (store) => store.getAll()); return prompts.sort((left, right) => right.updatedAt.localeCompare(left.updatedAt)); } async get(id: string) { return withStore<SavedPrompt | undefined>(PROMPTS, "readonly", (store) => store.get(id)); } async save(prompt: SavedPrompt) { await withStore(PROMPTS, "readwrite", (store) => store.put(prompt)); } async remove(id: string) { await withStore(PROMPTS, "readwrite", (store) => store.delete(id)); } async clear() { await withStore(PROMPTS, "readwrite", (store) => store.clear()); } }
export class IndexedDbComparisonRepository implements ComparisonRepository { async list() { const comparisons = await withStore<SavedComparison[]>(COMPARISONS, "readonly", (store) => store.getAll()); return comparisons.sort((left, right) => right.updatedAt.localeCompare(left.updatedAt)); } async get(id: string) { return withStore<SavedComparison | undefined>(COMPARISONS, "readonly", (store) => store.get(id)); } async save(comparison: SavedComparison) { await withStore(COMPARISONS, "readwrite", (store) => store.put(comparison)); } async remove(id: string) { await withStore(COMPARISONS, "readwrite", (store) => store.delete(id)); } async clear() { await withStore(COMPARISONS, "readwrite", (store) => store.clear()); } }
export class IndexedDbDiagnosticsRepository implements DiagnosticsRepository { async list() { const records = await withStore<DiagnosticRecord[]>(DIAGNOSTICS, "readonly", (store) => store.getAll()); return records.sort((left, right) => right.createdAt.localeCompare(left.createdAt)); } async get(id: string) { return withStore<DiagnosticRecord | undefined>(DIAGNOSTICS, "readonly", (store) => store.get(id)); } async save(record: DiagnosticRecord) { await withStore(DIAGNOSTICS, "readwrite", (store) => store.put(record)); } async remove(id: string) { await withStore(DIAGNOSTICS, "readwrite", (store) => store.delete(id)); } async clear() { await withStore(DIAGNOSTICS, "readwrite", (store) => store.clear()); } }
export class IndexedDbSecretRepository implements SecretRepository { async setSecret(ref: string, secret: string) { const encrypted = await encryptSecret(secret, await localMasterKey()); await withStore(SECRETS, "readwrite", (store) => store.put({ ref, ...encrypted })); } async getSecret(ref: string) { const payload = await withStore<(EncryptedSecret & { ref: string }) | undefined>(SECRETS, "readonly", (store) => store.get(ref)); return payload ? decryptSecret(payload, await localMasterKey()) : undefined; } async deleteSecret(ref: string) { await withStore(SECRETS, "readwrite", (store) => store.delete(ref)); } async hasSecret(ref: string) { return Boolean(await withStore(SECRETS, "readonly", (store) => store.getKey(ref))); } async clearSecrets() { await withStore(SECRETS, "readwrite", (store) => store.clear()); } }
export class IndexedDbSettingsRepository implements SettingsRepository { async get() { const record = await withStore<{ id: string; value: AppSettings } | undefined>(SETTINGS, "readonly", (store) => store.get(SETTINGS_KEY)); return { ...defaultSettings, ...record?.value, panelLayout: { ...defaultSettings.panelLayout, ...record?.value?.panelLayout } }; } async save(settings: AppSettings) { await withStore(SETTINGS, "readwrite", (store) => store.put({ id: SETTINGS_KEY, value: settings })); } }
export const providerRepository = new IndexedDbProviderRepository(); export const requestRepository = new IndexedDbRequestRepository(); export const promptRepository = new IndexedDbPromptRepository(); export const comparisonRepository = new IndexedDbComparisonRepository(); export const diagnosticsRepository = new IndexedDbDiagnosticsRepository(); export const secretRepository = new IndexedDbSecretRepository(); export const settingsRepository = new IndexedDbSettingsRepository();
