/** 精密工作台风格契约：比较执行器并行发送至用户选定 Provider；密钥仅由既有服务层瞬时读取，结果不携带原始 Provider payload。 */
import type { ComparePrompt, CompareResult, CompareStatus, CompareTarget } from "@/domain/compare";
import { MAX_COMPARE_TARGETS, safeCompareHeaders } from "@/domain/compare";
import type { AIRequest, ProviderConfig } from "@/domain/types";
import { normalizeProviderError, sendProviderRequest, streamProviderRequest } from "@/services/providerService";

const now = () => new Date().toISOString(); const createId = () => crypto.randomUUID ? crypto.randomUUID() : `${Date.now()}-${Math.random().toString(36).slice(2)}`;
export const initialResult = (target: CompareTarget): CompareResult => ({ targetId: target.id, providerId: target.providerId, providerName: target.providerName, model: target.model, displayName: target.displayName, status: "idle", content: "", metrics: { startedAt: now() } });
const requestFor = (target: CompareTarget, prompt: ComparePrompt): AIRequest => ({ id: `compare-request-${createId()}`, providerId: target.providerId, model: target.model, messages: prompt.messages.filter((message) => message.content.trim()), temperature: prompt.parameters.temperature, maxTokens: prompt.parameters.maxTokens, stream: prompt.parameters.stream, createdAt: now() });
const pricedMetrics = (target: CompareTarget, metrics: CompareResult["metrics"]) => { const input = metrics.usage?.inputTokens; const output = metrics.usage?.outputTokens; if (typeof input !== "number" || typeof output !== "number" || typeof target.inputPricePerMillion !== "number" || typeof target.outputPricePerMillion !== "number") return metrics; return { ...metrics, estimatedCost: (input * target.inputPricePerMillion + output * target.outputPricePerMillion) / 1_000_000 }; };
const asCompleted = (target: CompareTarget, result: CompareResult, response: Awaited<ReturnType<typeof sendProviderRequest>>): CompareResult => ({ ...result, status: "completed", content: response.content, httpStatus: response.httpStatus, headers: safeCompareHeaders(response.headers), metrics: pricedMetrics(target, response.metrics), completedAt: now() });
export type CompareUpdate = (result: CompareResult) => void;
export async function runCompareTarget(target: CompareTarget, prompt: ComparePrompt, provider: ProviderConfig, signal: AbortSignal, onUpdate: CompareUpdate): Promise<CompareResult> {
  const request = requestFor(target, prompt); let current: CompareResult = { ...initialResult(target), status: "sending", startedAt: request.createdAt, metrics: { startedAt: request.createdAt } }; onUpdate(current);
  try {
    if (!prompt.parameters.stream) { const response = await sendProviderRequest(request, provider, signal, "compare"); current = asCompleted(target, current, response); onUpdate(current); return current; }
    for await (const event of streamProviderRequest(request, provider, signal, "compare")) { if (event.type === "stream-started") { current = { ...current, status: "streaming" }; onUpdate(current); } if (event.type === "delta") { current = { ...current, status: "streaming", content: `${current.content}${event.value}` }; onUpdate(current); } if (event.type === "usage") { current = { ...current, metrics: { ...current.metrics, usage: event.usage } }; onUpdate(current); } if (event.type === "completed") { current = { ...current, status: "completed", content: event.response.content, httpStatus: event.response.httpStatus, headers: safeCompareHeaders(event.response.headers), metrics: pricedMetrics(target, event.response.metrics), completedAt: now() }; onUpdate(current); return current; } if (event.type === "aborted") { current = { ...current, status: "aborted", completedAt: now() }; onUpdate(current); return current; } if (event.type === "failed") { current = { ...current, status: "failed", error: event.error, completedAt: now() }; onUpdate(current); return current; } }
    return current;
  } catch (error) { const aborted = signal.aborted; current = { ...current, status: aborted ? "aborted" : "failed", error: aborted ? undefined : normalizeProviderError(error), completedAt: now() }; onUpdate(current); return current; }
}
export async function runComparison(targets: CompareTarget[], prompt: ComparePrompt, providers: ProviderConfig[], controllers: Map<string, AbortController>, onUpdate: CompareUpdate): Promise<PromiseSettledResult<CompareResult>[]> {
  const selected = targets.slice(0, MAX_COMPARE_TARGETS); if (!selected.length) return []; const tasks = selected.map((target) => { const provider = providers.find((item) => item.id === target.providerId); if (!provider) { const result = { ...initialResult(target), status: "failed" as CompareStatus, error: normalizeProviderError({ message: "Selected Provider is no longer configured." }), completedAt: now() }; onUpdate(result); return Promise.resolve(result); } const controller = new AbortController(); controllers.set(target.id, controller); return runCompareTarget(target, prompt, provider, controller.signal, onUpdate).finally(() => controllers.delete(target.id)); }); return Promise.allSettled(tasks);
}
