/** 精密工作台风格契约：Diagnostics 服务是唯一的本地错误采集入口，持久化前统一移除密钥、授权值与敏感 Header。 */
import type { DiagnosticContext, DiagnosticRecord, DiagnosticSource, ProviderHealth } from "@/domain/diagnostics";
import { safeDiagnosticHeaders, sanitizeText } from "@/domain/diagnostics";
import type { ProviderConfig, ProviderError } from "@/domain/types";
import { diagnosticsRepository } from "@/storage/indexedDb";

const makeId = () => crypto.randomUUID ? crypto.randomUUID() : `${Date.now()}-${Math.random().toString(36).slice(2)}`;
export async function recordDiagnostic(source: DiagnosticSource, error: ProviderError, context: DiagnosticContext = {}): Promise<DiagnosticRecord> { const record: DiagnosticRecord = { id: `diagnostic-${makeId()}`, createdAt: new Date().toISOString(), source, category: error.category, title: sanitizeText(error.title), status: error.title === "Request Stopped" ? "aborted" : "failed", retryable: error.retryable, error: { ...error, message: sanitizeText(error.message), description: sanitizeText(error.description), causes: error.causes.map(sanitizeText), actions: error.actions.map(sanitizeText), safeDetails: { ...error.safeDetails, headers: safeDiagnosticHeaders(context.headers) } }, context: { ...context, endpoint: sanitizeText(context.endpoint), requestId: sanitizeText(context.requestId), responseCode: sanitizeText(context.responseCode), headers: safeDiagnosticHeaders(context.headers) } }; await diagnosticsRepository.save(record); return record; }
export async function listDiagnostics() { return diagnosticsRepository.list(); }
export async function providerHealth(providers: ProviderConfig[]): Promise<ProviderHealth[]> { const records = await diagnosticsRepository.list(); return providers.map((provider) => { const latest = records.find((record) => record.context.providerId === provider.id); if (latest) return { providerId: provider.id, providerName: provider.name, status: latest.status === "failed" ? "failed" as const : "unknown" as const, lastCheckedAt: latest.createdAt, latencyMs: provider.lastLatencyMs, endpoint: provider.baseUrl, lastDiagnosticId: latest.id }; if (provider.status === "ready") return { providerId: provider.id, providerName: provider.name, status: "connected", lastCheckedAt: provider.lastTestedAt, latencyMs: provider.lastLatencyMs, endpoint: provider.baseUrl }; return { providerId: provider.id, providerName: provider.name, status: "unknown", endpoint: provider.baseUrl }; }); }
