/** 精密工作台风格契约：消息编排器是请求构造轨的核心，以明确 Role、顺序与局部操作替代聊天产品的气泡叙事。 */
import { BookmarkPlus, ChevronDown, ChevronUp, CopyPlus, Trash2 } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Textarea } from "@/components/ui/textarea";
import type { Message, MessageRole } from "@/domain/types";

const roles: MessageRole[] = ["system", "user", "assistant"];
const newMessage = (role: MessageRole): Message => ({ id: `message-${crypto.randomUUID ? crypto.randomUUID() : Date.now().toString(36)}`, role, content: "" });

export function MessageComposer({ messages, onChange, disabled }: { messages: Message[]; onChange: (messages: Message[]) => void; disabled?: boolean }) {
  const change = (index: number, update: Partial<Message>) => onChange(messages.map((message, messageIndex) => messageIndex === index ? { ...message, ...update } : message));
  const remove = (index: number) => onChange(messages.filter((_, messageIndex) => messageIndex !== index));
  const duplicate = (index: number) => { const source = messages[index]; onChange([...messages.slice(0, index + 1), { ...source, id: newMessage(source.role).id }, ...messages.slice(index + 1)]); };
  const move = (index: number, direction: -1 | 1) => { const target = index + direction; if (target < 0 || target >= messages.length) return; const next = messages.slice(); [next[index], next[target]] = [next[target], next[index]]; onChange(next); };
  return <div className="message-composer" aria-label="Message composer">{messages.map((message, index) => <article className={`message-card role-${message.role}`} key={message.id}><div className="message-card-bar"><label className="message-role"><span>ROLE</span><select aria-label={`Message ${index + 1} role`} value={message.role} disabled={disabled} onChange={(event) => change(index, { role: event.target.value as MessageRole })}>{roles.map((role) => <option key={role} value={role}>{role}</option>)}</select></label><div className="message-actions"><Button size="icon" variant="ghost" disabled={disabled || index === 0} onClick={() => move(index, -1)} aria-label="Move message up"><ChevronUp className="h-3.5 w-3.5" /></Button><Button size="icon" variant="ghost" disabled={disabled || index === messages.length - 1} onClick={() => move(index, 1)} aria-label="Move message down"><ChevronDown className="h-3.5 w-3.5" /></Button><Button size="icon" variant="ghost" disabled={disabled} onClick={() => duplicate(index)} aria-label="Duplicate message"><CopyPlus className="h-3.5 w-3.5" /></Button><Button size="icon" variant="ghost" disabled={disabled || messages.length === 1} onClick={() => remove(index)} aria-label="Delete message"><Trash2 className="h-3.5 w-3.5" /></Button></div></div><Textarea aria-label={`${message.role} message`} disabled={disabled} value={message.content} className={`message-textarea ${!message.content.trim() ? "message-empty" : ""}`} placeholder={message.role === "system" ? "Set operating context…" : message.role === "assistant" ? "Optional prior assistant context…" : "Write the request you want to test…"} onInput={(event) => { const element = event.currentTarget; element.style.height = "auto"; element.style.height = `${Math.max(92, element.scrollHeight)}px`; }} onChange={(event) => change(index, { content: event.target.value })} />{!message.content.trim() && <p className="message-validation">Content is required before sending.</p>}</article>)}<div className="add-message-row"><span>ADD MESSAGE</span>{roles.map((role) => <Button key={role} variant="outline" size="sm" disabled={disabled} onClick={() => onChange([...messages, newMessage(role)])}>+ {role}</Button>)}<Button variant="outline" size="sm" disabled={disabled || !messages.every((message) => message.content.trim())} onClick={() => { sessionStorage.setItem("openapi-playground-prompt-draft", JSON.stringify(messages)); window.location.assign("/prompts"); }}><BookmarkPlus className="h-3.5 w-3.5" /> Save prompt</Button></div></div>;
}
