/** 精密工作台风格契约：基础组件以状态可读性、边界清晰和紧凑信息密度为首要目标。 */
import { useMemo, useState, type ReactNode } from "react";
import { AlertCircle, CheckCircle2, ChevronRight, Clock3, Copy, DatabaseZap, Expand, Info, Loader2, Minimize2, Search, TriangleAlert, XCircle } from "lucide-react";
import { Button } from "@/components/ui/button";
import type { RequestStatus } from "@/domain/types";
import { cn } from "@/lib/utils";

const statusMeta: Record<RequestStatus, { label: string; icon: typeof Info; tone: string }> = { idle: { label: "Idle", icon: Info, tone: "neutral" }, loading: { label: "Loading", icon: Loader2, tone: "info" }, sending: { label: "Sending", icon: Loader2, tone: "info" }, streaming: { label: "Streaming", icon: Loader2, tone: "info" }, completed: { label: "Completed", icon: CheckCircle2, tone: "success" }, failed: { label: "Failed", icon: XCircle, tone: "error" }, aborted: { label: "Aborted", icon: AlertCircle, tone: "warning" }, retrying: { label: "Retrying", icon: Loader2, tone: "info" }, "no-provider": { label: "No provider", icon: TriangleAlert, tone: "warning" }, "no-model": { label: "No model", icon: TriangleAlert, tone: "warning" }, "network-error": { label: "Network error", icon: XCircle, tone: "error" }, "cors-error": { label: "CORS error", icon: XCircle, tone: "error" }, "invalid-configuration": { label: "Invalid configuration", icon: XCircle, tone: "error" } };
export function StatusIndicator({ status, compact = false }: { status: RequestStatus; compact?: boolean }) { const meta = statusMeta[status]; const Icon = meta.icon; return <span className={cn("status-indicator", `status-${meta.tone}`, compact && "status-compact")}><Icon aria-hidden="true" className={cn("h-3.5 w-3.5", ["loading", "sending", "streaming", "retrying"].includes(status) && "animate-spin")} />{meta.label}</span>; }
export function PanelHeading({ eyebrow, title, action }: { eyebrow?: string; title: string; action?: ReactNode }) { return <div className="panel-heading"><div><p className="eyebrow">{eyebrow || "Workspace"}</p><h2>{title}</h2></div>{action}</div>; }
export function MetricCard({ label, value, meta, icon }: { label: string; value: string; meta: string; icon?: ReactNode }) { return <div className="metric-card"><div className="metric-icon">{icon || <DatabaseZap className="h-4 w-4" />}</div><div><p>{label}</p><strong>{value}</strong><span>{meta}</span></div></div>; }
export function EmptyState({ icon, title, description, action, image }: { icon?: ReactNode; title: string; description: string; action?: ReactNode; image?: boolean }) { return <div className={cn("empty-state", image && "empty-state-illustrated")}>{image ? <img src="/manus-storage/empty-state-request-signal_46bcc80b.png" alt="Abstract request signal illustration" /> : <div className="empty-icon">{icon || <DatabaseZap className="h-5 w-5" />}</div>}<div><h3>{title}</h3><p>{description}</p></div>{action}</div>; }
export function CodeBlock({ code, language = "TEXT", onCopy }: { code: string; language?: string; onCopy?: () => void }) { const copy = () => { if (onCopy) onCopy(); else void navigator.clipboard?.writeText(code); }; return <div className="code-block"><div className="code-block-bar"><span>{language}</span><Button variant="ghost" size="sm" className="h-7 px-2" onClick={copy}><Copy className="h-3.5 w-3.5" /> Copy</Button></div><pre><code>{code}</code></pre></div>; }
const jsonValue = (value: unknown) => typeof value === "string" ? JSON.stringify(value) : value === null ? "null" : typeof value === "object" ? Array.isArray(value) ? `[${value.length}]` : "{…}" : String(value);
function JsonTree({ value, label, expanded, depth = 0 }: { value: unknown; label?: string; expanded: boolean; depth?: number }) { const object = value !== null && typeof value === "object"; if (!object) return <div className="json-leaf" style={{ paddingLeft: `${depth * 14}px` }}>{label && <span className="json-key">{label}: </span>}<span>{jsonValue(value)}</span></div>; const entries = Array.isArray(value) ? value.map((item, index) => [String(index), item] as const) : Object.entries(value as Record<string, unknown>); return <details className="json-node" open={expanded}><summary style={{ paddingLeft: `${depth * 14}px` }}><ChevronRight className="h-3 w-3" />{label && <span className="json-key">{label}: </span>}<span>{jsonValue(value)}</span></summary><div>{entries.map(([key, child]) => <JsonTree key={key} value={child} label={key} expanded={expanded} depth={depth + 1} />)}</div></details>; }
export function JsonViewer({ value, compact = false }: { value: unknown; compact?: boolean }) { const [pretty, setPretty] = useState(true); const [query, setQuery] = useState(""); const [expanded, setExpanded] = useState(true); const [version, setVersion] = useState(0); const serialized = useMemo(() => JSON.stringify(value, null, pretty ? 2 : 0), [value, pretty]); const matches = query ? serialized.toLowerCase().split(query.toLowerCase()).length - 1 : 0; if (compact) return <div className="json-viewer json-compact"><CodeBlock language="JSON" code={serialized} /></div>; return <div className="json-viewer"><div className="json-toolbar"><div className="json-search"><Search className="h-3.5 w-3.5" /><input aria-label="Search JSON" value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search JSON" />{query && <span>{matches}</span>}</div><div className="flex gap-1"><Button size="sm" variant={pretty ? "default" : "outline"} onClick={() => setPretty(true)}>Pretty</Button><Button size="sm" variant={!pretty ? "default" : "outline"} onClick={() => setPretty(false)}>Compact</Button><Button size="icon" variant="ghost" onClick={() => { setExpanded(true); setVersion((current) => current + 1); }} aria-label="Expand all JSON"><Expand className="h-3.5 w-3.5" /></Button><Button size="icon" variant="ghost" onClick={() => { setExpanded(false); setVersion((current) => current + 1); }} aria-label="Collapse all JSON"><Minimize2 className="h-3.5 w-3.5" /></Button><Button size="icon" variant="ghost" onClick={() => void navigator.clipboard?.writeText(serialized)} aria-label="Copy JSON"><Copy className="h-3.5 w-3.5" /></Button></div></div>{pretty ? <div className="json-tree" key={version}><JsonTree value={value} expanded={expanded} /></div> : <CodeBlock language="JSON" code={serialized} />}</div>; }
export function RequestTimeline({ status }: { status: RequestStatus }) { const current = status === "completed" ? 3 : ["sending", "streaming"].includes(status) ? 2 : status === "no-provider" ? 0 : 1; return <div className="request-timeline" aria-label="Request state timeline">{[["Prepared", Clock3], ["Sending", Loader2], ["Receiving", Loader2], ["Inspected", CheckCircle2]].map(([label, Icon], index) => { const StateIcon = Icon as typeof Clock3; return <div className={cn("timeline-step", index <= current && "is-active", index === current && "is-current")} key={label as string}><span><StateIcon className="h-3 w-3" /></span><small>{label as string}</small></div>; })}</div>; }
export function SignalTrace({ labels, active = 0, caption }: { labels: string[]; active?: number; caption?: string }) { return <div className="signal-trace" aria-label={caption || "Status trajectory"}>{caption && <span className="signal-caption">{caption}</span>}<div className="signal-track">{labels.map((label, index) => <div className={cn("signal-node", index <= active && "is-active", index === active && "is-current")} key={label}><i aria-hidden="true" /><small>{label}</small></div>)}</div></div>; }
